[debug] [2022-10-16T12:22:30.972Z] ----------------------------------------------------------------------
[debug] [2022-10-16T12:22:30.973Z] Command:       /usr/local/bin/node /Users/sophia/.npm-global/bin/firebase deploy
[debug] [2022-10-16T12:22:30.973Z] CLI Version:   11.14.4
[debug] [2022-10-16T12:22:30.973Z] Platform:      darwin
[debug] [2022-10-16T12:22:30.973Z] Node Version:  v16.18.0
[debug] [2022-10-16T12:22:30.974Z] Time:          Sun Oct 16 2022 21:22:30 GMT+0900 (대한민국 표준시)
[debug] [2022-10-16T12:22:30.974Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-10-16T12:22:31.003Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/undefined [none]
[debug] [2022-10-16T12:22:31.575Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/undefined 403
[debug] [2022-10-16T12:22:31.576Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/undefined {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2022-10-16T12:22:31.577Z] HTTP Error: 403, The caller does not have permission
[debug] [2022-10-16T12:22:31.742Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at responseToError (/Users/sophia/.npm-global/lib/node_modules/firebase-tools/lib/responseToError.js:49:12)
    at RetryOperation._fn (/Users/sophia/.npm-global/lib/node_modules/firebase-tools/lib/apiv2.js:288:77)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to get Firebase project undefined. Please make sure the project exists and your account has permission to access it.
